#!/usr/bin/env python3
"""
Personal AI Employee - Odoo Watcher Skill
Gold Tier - G-M5: Odoo MCP Integration

Purpose: Odoo accounting perception-only watcher (creates intake wrappers, NEVER executes actions)
Tier: Gold
Skill ID: G-M5-T02

CRITICAL: This is PERCEPTION-ONLY. It NEVER creates/posts invoices, NEVER registers payments,
NEVER calls ACTION MCP tools. It only creates intake wrappers in Business/Accounting/.

Features:
- Mock mode with templates/mock_odoo_invoices.json
- Real mode with MCP query tools (optional)
- PII redaction using mcp_helpers
- Checkpointing to avoid duplicates
- Privacy-safe intake wrappers
"""

import os
import sys
import json
import argparse
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Optional

# Import PII redaction helper
try:
    from personal_ai_employee.core.mcp_helpers import redact_pii, get_repo_root
except ImportError:
    import re
    def redact_pii(text: str) -> str:
        email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
        phone_pattern = r'(\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}'
        text = re.sub(email_pattern, '[EMAIL_REDACTED]', text)
        text = re.sub(phone_pattern, '[PHONE_REDACTED]', text)
        return text

    def get_repo_root() -> Path:
        """Fallback: find repo root"""
        current = Path(__file__).parent
        while current != current.parent:
            if (current / 'system_log.md').exists():
                return current
            current = current.parent
        return Path(__file__).parent.parent.parent.parent.parent


# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class OdooWatcher:
    """Odoo Watcher - Perception-only accounting alerts"""

    def __init__(self, config: Dict):
        self.config = config
        self.checkpoint_data = self._load_checkpoint()
        self.created_count = 0
        self.skipped_count = 0
        self.errors = []

    def _load_checkpoint(self) -> Dict:
        """Load checkpoint to avoid re-processing invoices"""
        checkpoint_path = self.config['checkpoint_path']
        if os.path.exists(checkpoint_path):
            try:
                with open(checkpoint_path, 'r') as f:
                    return json.load(f)
            except Exception as e:
                logger.error(f"Failed to load checkpoint: {e}")
                return {'processed_ids': [], 'last_run': None}
        return {'processed_ids': [], 'last_run': None}

    def _save_checkpoint(self):
        """Save checkpoint with processed invoice IDs"""
        checkpoint_path = self.config['checkpoint_path']
        self.checkpoint_data['last_run'] = datetime.now(timezone.utc).isoformat()

        # Keep only last 500 IDs
        if len(self.checkpoint_data['processed_ids']) > 500:
            self.checkpoint_data['processed_ids'] = self.checkpoint_data['processed_ids'][-500:]

        try:
            os.makedirs(os.path.dirname(checkpoint_path), exist_ok=True)
            with open(checkpoint_path, 'w') as f:
                json.dump(self.checkpoint_data, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to save checkpoint: {e}")

    def reset_checkpoint(self):
        """Reset checkpoint"""
        self.checkpoint_data = {'processed_ids': [], 'last_run': None}
        self._save_checkpoint()
        print("✓ Odoo checkpoint reset")

    def _create_remediation_task(self, title: str, description: str):
        """Create remediation task in Needs_Action/ when MCP fails"""
        try:
            timestamp = datetime.now(timezone.utc).strftime('%Y%m%d-%H%M')
            filename = f"remediation__mcp__odoo__{timestamp}.md"
            task_path = Path(self.config['base_dir']) / 'Needs_Action' / filename

            task_content = f"""---
id: remediation_odoo_{timestamp}
type: remediation
source: odoo_watcher
created_at: {datetime.now(timezone.utc).isoformat()}
priority: high
status: needs_action
---

# MCP Remediation: {title}

**Issue**: {title}
**Source**: Odoo Watcher (G-M5)
**Created**: {datetime.now(timezone.utc).isoformat()}

## Problem

{description}

## Suggested Actions

1. Check `.secrets/odoo_credentials.json` exists and has valid credentials
2. Verify Odoo instance is running and reachable
3. Review Docs/mcp_odoo_setup.md for setup instructions
4. Test connection: `python3 brain_mcp_registry_refresh_skill.py --server odoo --mock`
5. Re-run watcher in mock mode to verify intake wrapper creation works

## References

- Setup Guide: Docs/mcp_odoo_setup.md
- Credentials Template: .secrets/README.md
- MCP Registry: Logs/mcp_tools_snapshot_odoo.json

---
**Generated by**: odoo_watcher_skill.py
**Graceful Degradation**: Watcher continues running despite MCP failure
"""

            task_path.parent.mkdir(parents=True, exist_ok=True)
            task_path.write_text(task_content, encoding='utf-8')

            logger.info(f"Created remediation task: {filename}")
            self._append_log(f"Remediation task created: {title}")

        except Exception as e:
            logger.error(f"Failed to create remediation task: {e}")

    def _append_log(self, message: str):
        """Append to odoo_watcher.log"""
        log_path = self.config['log_path']
        try:
            os.makedirs(os.path.dirname(log_path), exist_ok=True)
            timestamp = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
            with open(log_path, 'a', encoding='utf-8') as f:
                f.write(f"[{timestamp}] {message}\n")
        except Exception as e:
            logger.warning(f"Could not write to log: {e}")

    def _create_intake_wrapper(self, invoice: Dict, dry_run: bool = False) -> Optional[str]:
        """Create intake wrapper in Business/Accounting/"""
        try:
            invoice_id = invoice['id']
            customer = invoice.get('customer_name', 'Unknown')
            timestamp = datetime.now(timezone.utc)
            timestamp_str = timestamp.strftime('%Y%m%d-%H%M')

            # Sanitize customer for filename
            customer_safe = customer.replace(' ', '_').replace('/', '_')[:30]

            filename = f"intake__odoo__{timestamp_str}__{customer_safe}.md"
            output_path = os.path.join(self.config['output_dir'], filename)

            if dry_run:
                print(f"[DRY-RUN] Would create: {filename}")
                return None

            # Extract invoice data
            invoice_number = invoice.get('invoice_number', 'N/A')
            amount = invoice.get('amount_total', 0)
            due_date = invoice.get('due_date', 'N/A')
            status = invoice.get('status', 'unknown')
            days_overdue = invoice.get('days_overdue', 0)
            is_urgent = days_overdue > 30 or status == 'overdue'

            # Create privacy-safe excerpt (PII redacted)
            excerpt = f"Invoice {invoice_number} for {customer}: ${amount:.2f}, {days_overdue} days overdue"
            excerpt = redact_pii(excerpt)

            # YAML frontmatter
            frontmatter = f"""---
id: odoo_invoice_{invoice_id}
source: odoo
received_at: {timestamp.isoformat()}
customer: {customer}
channel: odoo_accounting
invoice_id: {invoice_id}
invoice_number: {invoice_number}
excerpt: "{excerpt}"
status: pending
plan_required: {str(is_urgent).lower()}
pii_redacted: true
---

# Odoo Invoice Alert - {customer}

**⚠️ PERCEPTION-ONLY**: This is an intake wrapper. No Odoo actions have been taken.

## Invoice Details

**Customer**: {customer}
**Invoice Number**: {invoice_number}
**Amount**: ${amount:.2f}
**Due Date**: {due_date}
**Status**: {status}
**Days Overdue**: {days_overdue}
**Urgent**: {is_urgent}

## Invoice Summary

```
Invoice ID: {invoice_id}
Amount Total: ${amount:.2f}
Amount Due: ${invoice.get('amount_residual', amount):.2f}
Payment Status: {status}
```

## Suggested Next Steps

**If action required (payment follow-up, collection)**:
1. Review customer payment history
2. Create plan using `brain_create_plan` (Gold Tier - G-M5)
3. Request approval via `brain_request_approval`
4. Execute via `brain_execute_odoo_with_mcp` (Odoo actions)

**If informational only**:
- Archive to Done/ with note
- Update customer record if needed

## Privacy Notice

- PII in excerpt has been redacted for privacy
- Full invoice details preserved above for context
- Never commit this file to git (covered by .gitignore)

---
**Generated by**: odoo_watcher
**Watcher Version**: 1.0.0 (Gold Tier - G-M5)
**Checkpoint ID**: {self.checkpoint_data.get('last_run', 'initial')}
"""

            # Write file
            os.makedirs(self.config['output_dir'], exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(frontmatter)

            logger.info(f"Created intake wrapper: {filename}")
            return output_path

        except Exception as e:
            logger.error(f"Failed to create intake wrapper: {e}")
            self.errors.append(str(e))
            return None

    def _load_mock_invoices(self) -> List[Dict]:
        """Load mock invoices from fixture file"""
        fixture_path = self.config['mock_fixture_path']

        if not os.path.exists(fixture_path):
            raise FileNotFoundError(f"Mock fixture not found: {fixture_path}")

        try:
            with open(fixture_path, 'r') as f:
                invoices = json.load(f)

            if not isinstance(invoices, list):
                raise ValueError("Mock fixture must be a JSON array")

            logger.info(f"Loaded {len(invoices)} mock invoices")
            return invoices

        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON in mock fixture: {e}")

    def _fetch_invoices_real(self) -> List[Dict]:
        """
        Fetch invoices from real Odoo MCP using QUERY tools only.

        IMPORTANT: This ONLY calls QUERY tools (list_unpaid_invoices).
        NEVER calls ACTION tools (create_invoice, post_invoice, register_payment).

        Returns:
            List of invoice dicts
        """
        try:
            secrets_path = Path(self.config['base_dir']) / '.secrets' / 'odoo_credentials.json'

            if not secrets_path.exists():
                logger.warning("Odoo MCP credentials not found at .secrets/odoo_credentials.json")
                self._create_remediation_task(
                    "Odoo MCP credentials missing",
                    "MCP mode requested but credentials not configured. See Docs/mcp_odoo_setup.md"
                )
                return []

            # TODO: Real MCP client integration (G-M5)
            # For now, check credentials exist and return empty
            logger.info("Odoo MCP query tools integration pending (G-M5)")
            logger.info("Use --mode mock for testing until MCP servers are configured")
            return []

        except Exception as e:
            logger.error(f"Failed to fetch from Odoo MCP: {e}")
            self._create_remediation_task(
                "Odoo MCP query failed",
                f"Error: {e}\nCheck MCP server status and credentials."
            )
            return []

    def run(self, dry_run: bool = False, mock: bool = True, verbose: bool = False) -> Dict:
        """Run Odoo watcher"""
        start_time = datetime.now(timezone.utc)

        if verbose:
            logger.setLevel(logging.DEBUG)

        logger.info(f"Starting Odoo watcher (mock={mock}, dry_run={dry_run})")

        # Fetch invoices
        if mock:
            try:
                invoices = self._load_mock_invoices()
            except Exception as e:
                logger.error(f"Failed to load mock invoices: {e}")
                return {'success': False, 'error': str(e)}
        else:
            invoices = self._fetch_invoices_real()

        # Apply max_results limit
        max_results = self.config.get('max_results', 10)
        invoices = invoices[:max_results]

        logger.info(f"Processing {len(invoices)} invoices")

        # Process each invoice
        for invoice in invoices:
            inv_id = invoice.get('id')

            if not inv_id:
                logger.warning("Invoice missing ID, skipping")
                continue

            # Check if already processed
            if inv_id in self.checkpoint_data['processed_ids']:
                logger.debug(f"Skipping already processed invoice: {inv_id}")
                self.skipped_count += 1
                continue

            # Create intake wrapper
            output_path = self._create_intake_wrapper(invoice, dry_run=dry_run)

            if output_path:
                self.created_count += 1
                if not dry_run:
                    self.checkpoint_data['processed_ids'].append(inv_id)

        # Save checkpoint
        if not dry_run and self.created_count > 0:
            self._save_checkpoint()

        # Log summary
        duration = (datetime.now(timezone.utc) - start_time).total_seconds()
        summary = (
            f"Odoo watcher complete: "
            f"{len(invoices)} scanned, {self.created_count} created, "
            f"{self.skipped_count} skipped, {len(self.errors)} errors, "
            f"{duration:.2f}s"
        )

        self._append_log(summary)

        # Append to system_log.md
        try:
            with open('system_log.md', 'a', encoding='utf-8') as f:
                f.write(f"\n**[{start_time.isoformat()}]** {summary}\n")
        except:
            pass

        print(f"\n✅ {summary}")

        return {
            'success': True,
            'scanned': len(invoices),
            'created': self.created_count,
            'skipped': self.skipped_count,
            'errors': len(self.errors),
            'duration': duration
        }


def main():
    """Main CLI entry point"""
    parser = argparse.ArgumentParser(
        description='Odoo Watcher - Perception-only accounting alerts (Gold Tier - G-M5)'
    )
    parser.add_argument('--once', action='store_true', default=True,
                        help='Run once and exit (default)')
    parser.add_argument('--dry-run', action='store_true',
                        help='Simulate run without creating files')
    parser.add_argument('--mode', type=str, choices=['mock', 'mcp'], default='mock',
                        help='Data source mode: mock (default, uses templates/mock_odoo_invoices.json) or mcp (uses Odoo MCP QUERY tools)')
    parser.add_argument('--max-results', type=int, default=10,
                        help='Maximum invoices to process (default: 10)')
    parser.add_argument('--reset-checkpoint', action='store_true',
                        help='Reset checkpoint before running')
    parser.add_argument('--verbose', action='store_true',
                        help='Enable verbose logging')

    args = parser.parse_args()

    # Determine mock vs MCP mode
    use_mock = (args.mode == 'mock')

    config = {
        'base_dir': get_repo_root(),
        'checkpoint_path': 'Logs/odoo_watcher_checkpoint.json',
        'log_path': 'Logs/odoo_watcher.log',
        'output_dir': 'Business/Accounting',
        'max_results': args.max_results,
        'mock_fixture_path': 'templates/mock_odoo_invoices.json'
    }

    watcher = OdooWatcher(config)

    if args.reset_checkpoint:
        watcher.reset_checkpoint()

    result = watcher.run(dry_run=args.dry_run, mock=use_mock, verbose=args.verbose)

    return 0 if result['success'] else 1


if __name__ == "__main__":
    sys.exit(main())
